##################################################
# roll back to previous stable state
# use the previous image (ref: git main last sha)
# 
# author: ashraf minhaj
# mail  : ashraf_minhaj@yahoo.com
##################################################

name: 'rollback'

on: workflow_dispatch

jobs:
  rollback:
    name: rollback to prev sha
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Get commit SHAs
        id: get_commit_shas
        run: |
          # CURRENT_SHA=$(git rev-parse HEAD)
          # PREVIOUS_SHA=$(git rev-parse HEAD^)
          # echo "::set-output name=current_sha::${CURRENT_SHA}"
          # echo "::set-output name=previous_sha::${PREVIOUS_SHA}"
          echo "$GITHUB_CONTEXT"| jq '.event.commits[].id' | tail -2 | head -1 |sed 's/\"//g'
    
        